const GET_PUZZLE_REQUEST = 'puzzle/GET_PUZZLE_REQUEST';
const GET_PUZZLE_REQUEST_SUCCESS = 'puzzle/GET_PUZZLE_REQUEST_SUCCESS';
const GET_PUZZLE_REQUEST_FAILURE = 'puzzle/GET_PUZZLE_REQUEST_FAILURE';

export {
    GET_PUZZLE_REQUEST,
    GET_PUZZLE_REQUEST_SUCCESS,
    GET_PUZZLE_REQUEST_FAILURE,
};